<!-- BEGIN KEY -->
public class javax.naming.ContextNotEmptyException extends javax.naming.NamingException
<!-- END KEY -->
<!-- BEGIN DATA -->
 This exception is thrown when attempting to destroy a context that
 is not empty.
<p>
 If the program wants to handle this exception in particular, it
 should catch ContextNotEmptyException explicitly before attempting to
 catch NamingException. For example, after catching ContextNotEmptyException, 
 the program might try to remove the contents of the context before
 reattempting the destroy.
 <p>
 Synchronization and serialization issues that apply to NamingException
 apply directly here.

 @author Rosanna Lee
 @author Scott Seligman
 @version 1.8 05/11/17

 @see Context#destroySubcontext
 @since 1.3

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.naming.ContextNotEmptyException(String explanation)
<!-- END KEY -->
<!-- BEGIN DATA -->
 Constructs a new instance of ContextNotEmptyException using an
 explanation. All other fields default to null.

 @param	explanation	Possibly null string containing
 additional detail about this exception.
 @see java.lang.Throwable#getMessage

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.naming.ContextNotEmptyException()
<!-- END KEY -->
<!-- BEGIN DATA -->
 Constructs a new instance of ContextNotEmptyException with
 all name resolution fields and explanation initialized to null.

<!-- END DATA -->
