<!-- BEGIN KEY -->
public class javax.management.remote.JMXProviderException extends java.io.IOException
<!-- END KEY -->
<!-- BEGIN DATA -->
<p>当提供者存在所需的协议但由于某种原因不能使用时由 {@link JMXConnectorFactory} 和 {@link JMXConnectorServerFactory} 抛出的异常。</p>

@see JMXConnectorFactory#newJMXConnector
@see JMXConnectorServerFactory#newJMXConnectorServer
@since 1.5
@since.unbundled 1.0

<!-- END DATA -->
<!-- BEGIN KEY -->
private java.lang.Throwable javax.management.remote.JMXProviderException.cause
<!-- END KEY -->
<!-- BEGIN DATA -->
@serial An exception that caused this exception to be thrown.此字段可以为 null。
@see #getCause()

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.management.remote.JMXProviderException()
<!-- END KEY -->
<!-- BEGIN DATA -->
<p>构造一个不带指定详细消息的 <code>JMXProviderException</code>。</p>

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.management.remote.JMXProviderException(String message)
<!-- END KEY -->
<!-- BEGIN DATA -->
<p>构造带指定详细消息的 <code>JMXProviderException</code>。</p>

@param message 详细消息

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.management.remote.JMXProviderException(String message, Throwable cause)
<!-- END KEY -->
<!-- BEGIN DATA -->
<p>构造带指定详细消息和嵌套异常的 <code>JMXProviderException</code>。</p>

@param message 详细消息
@param cause 嵌套的异常

<!-- END DATA -->
