<!-- BEGIN KEY -->
public class javax.naming.AuthenticationException extends javax.naming.NamingSecurityException
<!-- END KEY -->
<!-- BEGIN DATA -->
当访问命名或目录服务发生验证错误时，抛出此异常。验证错误可能在（举例来说）用户程序提供的证书无效或者其他原因导致对需要命名/目录服务的用户进行验证失败时发生。
<p>
如果程序想要单独处理此异常，它应该在试图捕获 NamingException 之前显式捕获 AuthenticationException。在捕获 AuthenticationException 之后，通过使用适当的证书更新已解析上下文的环境属性，该程序可以重新尝试进行验证。
 <p>
应用于 NamingException 的同步和序列化问题在这里可以直接应用。

@author Rosanna Lee
@author Scott Seligman
@version 1.8 05/11/17
@since 1.3

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.naming.AuthenticationException(String explanation)
<!-- END KEY -->
<!-- BEGIN DATA -->
使用所提供的解释构造一个新的 AuthenticationException 实例。其他所有字段默认为 null。

@param	explanation	一个可能为 null 的字符串，包含有关此异常的附加详细信息。
@see java.lang.Throwable#getMessage

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.naming.AuthenticationException()
<!-- END KEY -->
<!-- BEGIN DATA -->
构造一个新的 AuthenticationException 实例。所有字段都被设置为 null。

<!-- END DATA -->
