<!-- BEGIN KEY -->
public class javax.naming.ContextNotEmptyException extends javax.naming.NamingException
<!-- END KEY -->
<!-- BEGIN DATA -->
当试图销毁一个不为空的上下文时，抛出此异常。
<p>
如果程序想要单独处理此异常，它应该在试图捕获 NamingException 之前显式捕获 ContextNotEmptyException。例如，在捕获 ContextNotEmptyException 之后，该程序可能试图在重新尝试销毁上下文之前移除该上下文的内容。
 <p>
应用于 NamingException 的同步和序列化问题在这里可以直接应用。

@author Rosanna Lee
@author Scott Seligman
@version 1.8 05/11/17

@see Context#destroySubcontext
@since 1.3

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.naming.ContextNotEmptyException(String explanation)
<!-- END KEY -->
<!-- BEGIN DATA -->
使用解释构造一个新的 ContextNotEmptyException 实例。其他所有字段都默认为 null。

@param	explanation	可能为 null 的字符串，包含有关此异常的附加详细信息。
@see java.lang.Throwable#getMessage

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.naming.ContextNotEmptyException()
<!-- END KEY -->
<!-- BEGIN DATA -->
构造一个新的 ContextNotEmptyException 实例，将解释和所有名称解析字段初始化为 null。

<!-- END DATA -->
