<!-- BEGIN KEY -->
public class javax.management.RuntimeErrorException extends javax.management.JMRuntimeException
<!-- END KEY -->
<!-- BEGIN DATA -->
当代理中发生 <CODE>java.lang.Error</CODE> 时，必须捕获它并作为 <CODE>RuntimeErrorException</CODE> 重新抛出。

@since 1.5

<!-- END DATA -->
<!-- BEGIN KEY -->
private java.lang.Error javax.management.RuntimeErrorException.error
<!-- END KEY -->
<!-- BEGIN DATA -->
@serial 封装的 {@link Error}

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.management.RuntimeErrorException(Error e)
<!-- END KEY -->
<!-- BEGIN DATA -->
默认的构造方法。

@param e 包装的错误。

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.management.RuntimeErrorException(Error e, String message)
<!-- END KEY -->
<!-- BEGIN DATA -->
允许指定特定错误消息的构造方法。

@param e 包装的错误。
@param   message   详细消息。

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.lang.Error javax.management.RuntimeErrorException.getTargetError()
<!-- END KEY -->
<!-- BEGIN DATA -->
返回抛出的实际 {@link Error}。

@return 包装的 {@link Error}。

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.lang.Throwable javax.management.RuntimeErrorException.getCause()
<!-- END KEY -->
<!-- BEGIN DATA -->
返回抛出的实际 {@link Error}。

@return 包装的 {@link Error}。

<!-- END DATA -->
